BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TASKS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"content"	TEXT NOT NULL,
	"x"	REAL NOT NULL,
	"y"	REAL NOT NULL,
	"world_ID"	INTEGER NOT NULL,
	"status"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("world_ID") REFERENCES "WORLDS"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "TASK_DEP" (
	"dependency_ID"	INTEGER NOT NULL,
	"dependant_ID"	INTEGER NOT NULL,
	UNIQUE("dependency_ID","dependant_ID"),
	FOREIGN KEY("dependant_ID") REFERENCES "TASKS"("ID") ON DELETE CASCADE,
	FOREIGN KEY("dependency_ID") REFERENCES "TASKS"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "VERSION" (
	"version"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "WORLDS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"order_num"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
